name: Generate API
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Academic Year'
        required: false
  schedule:
    - cron: '0 0/1 * * *'

concurrency:
  group: generate

jobs:
  tick:
    name: Tick
    runs-on: ubuntu-latest
    concurrency: tick-lock
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: pysetup
        with:
          python-version: '3.11'
          cache: pip

      - name: setup-python requires
        if: ${{ steps.pysetup.outputs.cache-hit }} == 'false'
        run: pip install -r requirements.txt

      - name: Set Timezone
        run: timedatectl set-timezone Asia/Taipei

      - name: Clone
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: data

      - name: Start
        run: python main.py start

      - name: Deploy
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          if [ -d "data" ]; then
            cd data

            git add -A
            git commit -m "🚀 Update data for data"
            git push -f https://_:"$token"@$repository master:"gh-pages"

            cd -
          fi
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: github.com/${{ github.repository }}
