name: Generate API
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Academic Year'
        required: false
  # schedule:
  #   - cron: '0 0/1 * * *'

concurrency:
  group: generate

jobs:
  tick:
    name: Tick
    runs-on: ubuntu-latest
    concurrency: tick-lock
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-

      - uses: actions/setup-python@v5
        id: pysetup
        with:
          python-version: '3.11'
          cache: pip

      - name: setup-python requires
        if: !steps.pysetup.outputs.cache-hit
        run: pip install -r requirements.txt

      - name: Start
        run: python main.py start
